### ISSUE TITLE
TypeError: stringInject is not a function

### ISSUE THREAD

**Issue by VaLThieL** [tjcafferkey/stringinject#1]
Hi I'm getting this error

TypeError: stringInject is not a function

I try with
`const stringInject = require(stringInject);`
and
`const stringInject = require(stringinject);`

but nothing work, the npm install work properly

**Comment by tjcafferkey** [comment]
Hi, are you putting stringInject within a string when you require it in? Like below:

`var stringInject = require('stringinject');`

Also, are you getting any errors (either when building or within the console) because if so please post them here and it will give me more detail surrounding the issue.

Thanks,

Tom.

**Comment by VaLThieL** [comment]
Yes I do, try as var too but not works, I'm not getting any error on installation

**Comment by amprodes** [comment]
Am having the same issue "TypeError: stringInject is not a function" this is my code
 
	var message = stringInject('hello {realname} how are you today at {cposition}', {realname: real_name, cposition: current_position});
       console.log(message);

**Comment by pskopelitis** [comment]
using this works:

`const stringInject = require("stringinject").default;`
